### PR TITLE
do not replace old docs if rebuild failed

### LINKED ISSUE #2675: do not replace old docs if rebuild failed
### Crate name

rand

### Build failure link

https://docs.rs/crate/rand/latest/builds

### Additional details

It seems that `rand` 0.8.5 docs got rebuilt yesterday? Strange; I haven't seen docs.rs just rebuild old docs before. And unfortunately, the rebuild fails due to a nightly feature which got changed since then.

Can you reinstate the old docs build please?

CC https://github.com/rust-random/rand/issues/1528

### PR DESCRIPTION
**Pull request by syphar**
Resolves #2675 

In case of pre-build errors we already are just returning from the method via `?`, 
so I thought we could just do the same in this case, after moving `finish_build` above the `finish_release` call I want to skip.

### CODE REVIEW

File: src/db/add_package.rs [hunk 1]
```diff
@@ -447,7 +447,7 @@ fn get_readme(pkg: &MetadataPackage, source_dir: &Path) -> Result<Option<String>
 }
 
 fn get_rustdoc(pkg: &MetadataPackage, source_dir: &Path) -> Result<Option<String>> {
-    if let Some(src_path) = &pkg.targets[0].src_path {
+    if let Some(src_path) = &pkg.targets.first().and_then(|t| t.src_path.clone()) {
```
Comment (GuillaumeGomez) [inline src/db/add_package.rs:450]:
```suggestion
    if let Some(src_path) = &pkg.targets.first().map(|t| &t.src_path) {
```

Comment (syphar) [reply src/db/add_package.rs:450]: since `t.src_path` is an `Option<String>`, 

this would change the matched `src_path` from `&String` to `&Option<String>`

Comment (GuillaumeGomez) [reply src/db/add_package.rs:450]: What about:

```suggestion
    if let Some(src_path) = &pkg.targets.first().and_then(|t| &t.src_path) {
```

?

Comment (syphar) [reply src/db/add_package.rs]: nope :) 

grafik

But thinking about it, you're right, we didn't need the clone. Thanks for being persistent :) 

( added a commit)

**Review by GuillaumeGomez — APPROVED** [review]

File: src/db/add_package.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/db/add_package.rs]: Haha. In my wrongness it allowed you to see a better path :D
