### PR TITLE
fix archive index caching for source archives, don't ignore source fetch errors

### LINKED ISSUE #2322: Problem retrieving source files for rebuilt crate
When investigating why we just had the build queue locked I noticed a few errors like these in the logs:

```
Nov 18 19:08:14 docsrs cratesfyi[12087]: 2023-11-18T19:08:14.514737Z  WARN crate_details_handler{params=CrateDetailHandlerParams { name: "atuin", version: Some("17.0.1") } repository_stats_updater=Repo
Nov 18 19:08:14 docsrs cratesfyi[12087]: Caused by:
Nov 18 19:08:14 docsrs cratesfyi[12087]:     0: fetching Cargo.toml from atuin 17.0.1 (archive: true)
Nov 18 19:08:14 docsrs cratesfyi[12087]:     1: bzip2: bz2 header missing
```

Trying to browse the source files in this crate, many of them are not showing any content, like https://docs.rs/crate/atuin/17.0.1/source/Cargo.toml

Presumably this assumption is not correct

https://github.com/rust-lang/docs.rs/blob/62c620e51fcb2ef4f62571044aa510a3e16d9843/src/storage/mod.rs#L215

even though the contents of the archive don't change, we do upload a new source archive which may have different file offsets for many reasons.

### PR DESCRIPTION
**Pull request by syphar**
Fixes #2322 while also now reporting the error to sentry so we would have regognized the issue earlier.

### CODE REVIEW

File: src/web/source.rs [hunk 1]
```diff
@@ -222,34 +222,64 @@ pub(crate) async fn source_browser_handler(
...
     .await?;
 
     // try to get actual file first
     // skip if request is a directory
-    let blob = if !path.ends_with('/') {
-        storage
-            .fetch_source_file(&name, &version, &path, archive_storage)
+    let blob = if !path.ends_with('/')
+        && storage
+            .source_file_exists(
```
Comment (Nemo157) [inline src/web/source.rs:261]: Instead of pre-checking here, can we just attempt to fetch and then map a `PathNotFoundError` to `None`.

Comment (syphar) [reply src/web/source.rs]: generally the existance check would be relatively fast because it's just using the local archive index, but this is still a valid point, and I updated the code.

**Comment by syphar** [comment]
@Nemo157 ready for another check. 

I also rebased on master and _changed_ the initial commit to be based on #2326.

File: src/web/source.rs [hunk 2]
```diff
@@ -241,10 +252,26 @@ pub(crate) async fn source_browser_handler(
...
+                &path,
+                row.archive_storage,
+            )
             .await
-            .ok()
+            .context("error fetching source file")
+        {
+            Ok(blob) => Some(blob),
+            Err(err) => {
+                if err.downcast_ref::<PathNotFoundError>().is_some() {
```
Comment (Nemo157) [inline src/web/source.rs:268]:
```suggestion
                if err.is::<PathNotFoundError>() {
```

**Review by Nemo157 — APPROVED** [review]
