### PR TITLE
remove postgres dependencies, cleanup remaining usages

### LINKED ISSUE #874: Switch to sqlx for compile-time checked queries
A common source of outages is an incorrect query with no tests (https://github.com/rust-lang/docs.rs/pull/862, https://github.com/rust-lang/docs.rs/pull/829, https://github.com/rust-lang/docs.rs/pull/648, etc). While it's good to have tests for all queries, it's not always feasible (especially until #822 is fixed). [SQLx](http://docs.rs/sqlx) offers that advantage that it can check all queries at build time without having to write a test for that specific query. It is also fully async (cc @Kixiron), although that might mean we have to wait until we switch to tokio 0.2.

To avoid needless database connections, this should only connect to the database when a query is changed or added, or a schema change is made: https://github.com/launchbadge/sqlx/pull/249. During CI it should always connect to the database.

### PR DESCRIPTION
**Pull request by syphar**
Resolves #874 

includes the changes from https://github.com/rust-lang/docs.rs/pull/2617

### CODE REVIEW

File: src/utils/consistency/db.rs [hunk 1]
```diff
@@ -30,23 +34,19 @@ pub(super) fn load(conn: &mut postgres::Client, config: &Config) -> Result<Crate
                  releases.id IS NULL
              )
          ) AS inp
-         ORDER BY name, version",
-        iter::once(config.build_attempts as i32),
-    )?;
+         ORDER BY name, version"#,
+        config.build_attempts as i32,
+    )
+    .fetch_all(conn)
```
Comment (syphar) [inline src/utils/consistency/db.rs:40]: this has higher memory usage than the implementation before, since `fetch_all` loads everything into a `Vec`. 

But since I still wanted to use `Itertools::chunk_by` below, I thought we bite the bullet, since we have enough memory. 

( I'll optimize it later)

**Review by GuillaumeGomez — APPROVED** [review]
