### PR TITLE
split service&instance metrics, serve metrics for build-server & watcher

### LINKED ISSUE #795: Split apart web server and build server
Currently, all web requests are served from the same server that performs the crate builds. This has given us trouble in the past, since builds consume a lot of resources, driving up response times for web requests. It would be useful to instead have different servers for the website and builds.

Possible implementation:
- The web server continues having primary access to the database. Builders don't have access at all, but instead receive webhooks (or similar) telling them to start a build. When the build finishes, they report back to the main server.
- We have a 'heartbeat' mechanism similar to crater: if a build server doesn't send a message to the web server in 5 minutes, we mark it as crashed
- We have a new state for crates in the queue: `queued`, `finished`, and `assigned`, where `assigned` means there is a build server currently building that crate (#1011).

Benefits:
- We could build multiple crates at a time much more easily (alleviating some of the trouble from #343) just by having more build servers. This requires #1011 first.
- We could potentially target more architectures without cross-compiling, by having build servers that are e.g. hosted on ARM.
- We could eventually share some build resources with crater.

@pietroalbini has experience with implementing this for crater and is helping a lot with the design aspect.

### PR DESCRIPTION
**Pull request by syphar**
* split service & instance metrics into separate objects, serve them via separate endpoints
* add a small webserver to serve metrics for the build-server & registry watcher

IMO this is the last piece missing to close #795 , while touching it I also split the metrics (#1755), so collecting the metrics could be optimized. 

I also tried to find a non-macro approach for the metrics definition & registration, perhaps migrating the instance-metrics too. (I'm taking ideas how to improve this further)

### CODE REVIEW

File: src/bin/cratesfyi.rs [hunk 1]
```diff
@@ -101,6 +101,8 @@ enum CommandLine {
     },
 
     StartRegistryWatcher {
+        #[arg(name = "SOCKET_ADDR", default_value = "0.0.0.0:3000")]
+        metric_server_socket_addr: String,
```
Comment (Nemo157) [inline src/bin/cratesfyi.rs:105]: You can use `SocketAddr` here to get clap to parse it and give a good error message.

File: src/bin/cratesfyi.rs [hunk 2]
```diff
@@ -112,7 +114,10 @@ enum CommandLine {
         cdn_invalidator: Toggle,
     },
 
-    StartBuildServer,
+    StartBuildServer {
+        #[arg(name = "SOCKET_ADDR", default_value = "0.0.0.0:3000")]
+        metric_server_socket_addr: String,
```
Comment (Nemo157) [inline src/bin/cratesfyi.rs:119]: Same here.

File: src/build_queue.rs [hunk 3]
```diff
@@ -206,7 +206,7 @@ impl BuildQueue {
                 to_process.name, to_process.version
             )
         });
-        self.metrics.total_builds.inc();
+        self.metrics.instance.total_builds.inc();
```
Comment (Nemo157) [inline src/build_queue.rs:209]: Should we change these to take `InstanceMetrics` instead of `Metrics`? (Probably by moving the `Arc` inside the `Metrics` so each is shared individually).

File: src/metrics/mod.rs [hunk 4]
```diff
@@ -180,18 +181,112 @@ impl RecentlyAccessedReleases {
...
+    pub failed_crates_count: IntGauge,
+    pub queue_is_locked: IntGauge,
+    pub queued_crates_count_by_priority: IntGaugeVec,
+    pub queued_cdn_invalidations_by_distribution: IntGaugeVec,
+
+    registry: prometheus::Registry,
+}
+
+impl ServiceMetrics {
+    pub fn new() -> Result<Self, prometheus::Error> {
```
Comment (Nemo157) [inline src/metrics/mod.rs:240]: Is this just doing what the macro generates, or is there a reason the `InstanceMetrics` can use it but this one can't?

File: src/web/metrics.rs [hunk 5]
```diff
@@ -2,42 +2,65 @@ use crate::{
...
 
+async fn fetch_and_render_metrics(
+    fetcher: impl Fn() -> Result<Vec<MetricFamily>> + Send + 'static,
+) -> AxumResult<impl IntoResponse> {
+    let metrics_families = spawn_blocking(fetcher).await?;
+
+    let mut buffer = Vec::new();
+    TextEncoder::new()
+        .encode(&metrics_families, &mut buffer)
+        .context("error encoding metrics")?;
```
Comment (Nemo157) [inline src/web/metrics.rs:26]: I would move the encoding inside the spawned task too, no need to block the async threads on it if we're already doing cross-task stuff.

File: src/web/mod.rs [hunk 6]
```diff
@@ -270,6 +273,47 @@ pub(crate) fn build_axum_app(
...
+    tracing::info!(
+        "Starting metrics web server on `{}:{}`",
+        axum_addr.ip(),
+        axum_addr.port()
+    );
+
+    let metrics_axum_app = build_metrics_axum_app(context)?.into_make_service();
+    let runtime = context.runtime()?;
+
+    thread::spawn(move || {
```
Comment (Nemo157) [inline src/web/mod.rs:302]: Do we need to spawn a thread, or can we just `runtime.spawn` this given that the runtime is kept alive by the context?

File: src/bin/cratesfyi.rs (hunk 1 above)
Comment (syphar) [reply src/bin/cratesfyi.rs]: I didn't know about that, I updated the arguments & their usages.

File: src/bin/cratesfyi.rs (hunk 2 above)
Comment (syphar) [reply src/bin/cratesfyi.rs]: see above

File: src/web/mod.rs (hunk 6 above)
Comment (syphar) [reply src/web/mod.rs]: valid point, updated

File: src/web/metrics.rs (hunk 5 above)
Comment (syphar) [reply src/web/metrics.rs]: valid, done

File: src/metrics/mod.rs (hunk 4 above)
Comment (syphar) [reply src/metrics/mod.rs:242]: I honestly don't fully remember the details. 

I think it was a combination: 
- the service metrics would have needed more special-casing in the macro (like cdn invalidation times), or would have needed a refactor
- the special-casing makes it harder to reason about the code IMO.

File: src/build_queue.rs (hunk 3 above)
Comment (syphar) [reply src/build_queue.rs:207]: Design-wise you're right, though this then would need this split across all usages of metrics. 

I'll give it a try, and see how much breaks

Comment (syphar) [reply src/build_queue.rs]: I updated the code with what I think you meant, thanks for the push!

File: src/web/mod.rs [hunk 7]
```diff
@@ -65,7 +66,7 @@ pub(crate) fn encode_url_path(path: &str) -> String {
     utf8_percent_encode(path, PATH).to_string()
 }
 
-const DEFAULT_BIND: &str = "0.0.0.0:3000";
+const DEFAULT_BIND: SocketAddr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 8080);
```
Comment (Nemo157) [inline src/web/mod.rs:68]: Purposefully changed the port number?

Comment (syphar) [reply src/web/mod.rs:68]: oh ;) good catch! also fixed the ip

**Review by Nemo157 — APPROVED** [review]

**Comment by syphar** [comment]
thank you for the help @Nemo157 ❤️
