### PR TITLE
Fix feature flags count

### LINKED ISSUE #1284: Weird feature flag counting behavior
https://docs.rs/crate/serde/1.0.123/features

```
This version has 7 feature flags, 2 of them enabled by default.

default
    std 
std
    This feature flag does not enable additional features.
```

>  (but really should be "3 feature flags, 2 of them enabled by default" cause sha2 is a private flag) - @Nemo157 

I feel like it should mention that `default` is counted as a feature flag by itself.

I don't quite know what is a "private flag" but I believe the counting behavior is a bit weird.

Also, currently how the feature flags being rendered is quite weird, the "    This feature flag does not enable additional features." part is especially long and cannot easily differentiate between those that have feature flag.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1284.

### CODE REVIEW

File: src/web/features.rs [hunk 1]
```diff
@@ -116,6 +116,24 @@ impl FeaturesPage {
     pub(crate) fn use_direct_platform_links(&self) -> bool {
         true
     }
+
+    pub(crate) fn nb_enabled_default_features(&self) -> usize {
```
Comment (syphar) [inline src/web/features.rs:120]: nit: what does `nb_` mean in the function name? Is there a better name?

**Review by syphar — CHANGES_REQUESTED** [review]
awesome, thanks! 

only one (optional) thing, 
also CI fails.

File: src/web/features.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/web/features.rs:120]: It means "number". Gonna find a better name.

Comment (fbstj) [reply src/web/features.rs:120]: `count_` makes sense?

Comment (GuillaumeGomez) [reply src/web/features.rs:120]: I remove `nb_` and added `_count` at the end. But glad to see I'm not the only one with this idea. :)

**Comment by GuillaumeGomez** [comment]
Updated.

**Review by syphar — APPROVED** [review]
