### PR TITLE
Keep arguments in redirections

### LINKED ISSUE #2786: docs.rs removes query parameters on redirect
When requesting a url on docs.rs that gets redirected e.g. because the wrong version of -/_ was used, e.g. <https://docs.rs/embedded_graphics/0.8.0/embedded_graphics>, and you add query parameters, e.g. <https://docs.rs/embedded_graphics/0.8.0/embedded_graphics/?search=pixel>, you get redirected to <https://docs.rs/embedded-graphics/0.8.0/embedded_graphics/> with the query parameter stripped. I think the redirect should instead go to <https://docs.rs/embedded-graphics/0.8.0/embedded_graphics/?search=pixel>, i.e. keeping the query parameters.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #2786.

I created a new type to ensure that the escaping was done only once.

### CODE REVIEW

File: src/web/rustdoc.rs [hunk 1]
```diff
@@ -362,18 +362,26 @@ pub(crate) async fn rustdoc_html_server_handler(
     // Pages generated by Rustdoc are not ready to be served with a CSP yet.
     csp.suppress(true);
 
+    fn get_query_and_fragment(uri: &Uri) -> Option<&str> {
```
Comment (syphar) [inline src/web/rustdoc.rs:365]: from what I know, the fragment will never reach the server in any case. So just using the `RawQuery` extractor and passing its content to the redirect is good enough.

**Review by syphar — CHANGES_REQUESTED** [review]
we probably also should update the `rustdoc_redirector_handler` to forward the query args. 

Also we should see if the [trailing-slash-redirect](https://docs.rs/axum-extra/latest/axum_extra/routing/trait.RouterExt.html#tymethod.route_with_tsr) we're using also forwards the query (not sure if we should spend time on fixing it if it doesn't).

File: src/web/rustdoc.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/web/rustdoc.rs:365]: Noted!

**Comment by GuillaumeGomez** [comment]
Only using the `query` now.

**Comment by syphar** [comment]
> we probably also should update the `rustdoc_redirector_handler` to forward the query args.

did you intentionally leave out the redirector handler?

**Comment by GuillaumeGomez** [comment]
There was only one case which needed it as most of them are already using `redirect_to_doc` which adds redirections.

File: src/web/rustdoc.rs [hunk 2]
```diff
@@ -253,7 +253,11 @@ pub(crate) async fn rustdoc_redirector_handler(
         .into_response())
     } else {
         Ok(axum_cached_redirect(
-            format!("/crate/{crate_name}/{}", matched_release.req_version),
+            EscapedURI::new(
+                &format!("/crate/{crate_name}/{}", matched_release.req_version),
+                uri.query(),
```
Comment (syphar) [inline src/web/rustdoc.rs:258]: I'm missing a test for this updated behaviour here.

**Review by syphar — CHANGES_REQUESTED** [review]
Nearly there, thank you for working on this!

**Comment by syphar** [comment]
generally: with all the github noise I typically work with the [personal "review requests" tab](https://github.com/pulls/review-requested) quite much, and check these more often than notifications in general, so re-requesting a review when it's ready again really helps me. 

( I'll see the other notifications later too, but not as fast)

**Comment by GuillaumeGomez** [comment]
> generally: with all the github noise I typically work with the [personal "review requests" tab](https://github.com/pulls/review-requested) quite much, and check these more often than notifications in general, so re-requesting a review when it's ready again really helps me.
> 
> ( I'll see the other notifications later too, but not as fast)

Noted!

File: src/web/rustdoc.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/web/rustdoc.rs:258]: I can't figure out what's the URL for it. I tried `/crate/sysinfo/0.29.0?search=q` and `/crate/sysinfo/0.40.0?search=q` and both have the query arguments even before this change. Any idea?

Comment (syphar) [reply src/web/rustdoc.rs:258]: the redirector is behind URLs like `/sysinfo`

Comment (syphar) [reply src/web/rustdoc.rs:258]: ah wait, you're searching for an example for this specific `else` part

Comment (syphar) [reply src/web/rustdoc.rs:258]: you will only reach it when `rustdoc_status` is `false`. 

That being said, should we update the `query_pairs` in the `redirect_to_doc` function in here too to your new `EscapedURI`?

Comment (GuillaumeGomez) [reply src/web/rustdoc.rs:258]: > you will only reach it when `rustdoc_status` is `false`.

Can't find a way to write a test with this case. Do we have a test with this situation by any chance?

Comment (GuillaumeGomez) [reply src/web/rustdoc.rs:258]: Nice, thanks a lot!

**Comment by GuillaumeGomez** [comment]
Added your test. :)

**Review by syphar — APPROVED** [review]
