### PR TITLE
Fix unwanted "empty-library" appearance

### LINKED ISSUE #1313: Publishing a crate without dependencies causes a `empty_library` dependency.
When publishing a no_std crate without dependencies, it will add an `empty_library` to the crates on [docs.rs].

Reproduction steps:
1. Publish a no_std library without dependencies.
2. The docs.rs page will now have a `empty_library` in the crates.

This seems like a rather awkward way to tell the reader the crate has no dependencies. Now if you click any deeper into the documentation, on the left (under the crates header) the empty_library will be a clickable link that leads to a dead link.

This is what I mean: [Link to CRC8-RS Docs](https://docs.rs/crc8-rs/1.0.0/crc8_rs/fn.fetch_crc8.html)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1313.

cc @Nemo157 @jyn514 

We will need to remove the files into the existing dirs too I guess?

### CODE REVIEW

File: src/docbuilder/rustwide_builder.rs [hunk 1]
```diff
@@ -237,6 +237,14 @@ impl RustwideBuilder {
                 for (&file, versioned) in files {
                     let segments = file.rsplitn(2, '.').collect::<Vec<_>>();
                     let file_name = if versioned {
+                        if segments[0] == "js"
+                            && ["crates", "search-index"].iter().any(|x| *x == segments[1])
```
Comment (Nemo157) [inline src/docbuilder/rustwide_builder.rs:241]: Couldn't you just remove `crates.js` from the `ESSENTIAL_FILES_VERSIONED` list above?

Comment (Nemo157) [reply src/docbuilder/rustwide_builder.rs:241]: This will also cause https://github.com/rust-lang/docs.rs/issues/1300 to reoccur, we might need to generate a `crates.js` that sets an empty array or something (or really it should come from each doc build, not the essential files, to support multi-crate packages in the future).

**Comment by Nemo157** [comment]
Looking back into #1300 more, what I don't understand is why it is trying to load a global `crates.js` instead of a local one for each crate: https://docs.rs/crates-20210304-1.52.0-nightly-45b3c2851.js does not exist but https://docs.rs/syn/1.0.61/crates-20210304-1.52.0-nightly-45b3c2851.js does. Are we incorrectly rewriting this url? (note that `search-index.js` _is_ loaded locally from the current version)

File: src/docbuilder/rustwide_builder.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/docbuilder/rustwide_builder.rs:241]: It should definitely come from each doc build.

**Comment by GuillaumeGomez** [comment]
@Nemo157 This fix works too. Now the problem is that the `crates.js` path is invalid. I don't how we generate it correctly for `search-index.js` and `source-files.js`. Any idea maybe?

**Comment by Nemo157** [comment]
This can be merged once https://github.com/rust-lang/rust/pull/83094 is in a nightly, that on its own should fix the issue, this should just avoid copying a file that shouldn't actually be part of the essential files (merging it before that would cause the errors from #1300 again, the symptom in #1313 is less bad).

**Comment by jyn514** [comment]
> This can be merged once [rust-lang/rust#83094](https://github.com/rust-lang/rust/pull/83094) is in a nightly, that on its own should fix the issue, this should just avoid copying a file that shouldn't actually be part of the essential files (merging it before that would cause the errors from #1300 again, the symptom in #1313 is less bad).

@Nemo157 https://docs.rs/crc8-rs/1.1.0/crc8_rs/ was built with rustc 1.52.0-nightly (36f1f04f1 2021-03-17), but it still shows empty-library and loads crates.js from the suffix path. That makes me worry that deploying this will break all builds again.

**Comment by jyn514** [comment]
Hmm, it does seem to work locally though.

**Comment by GuillaumeGomez** [comment]
I think a file needs to be removed somewhere on our end.
