### PR TITLE
purge all rustwide build directories before each build

### LINKED ISSUE #820: Target directories are not purged after build failures
While there is code to purge target directories once a build finishes, if an error happens during the build that code is never executed, leaking disk space. We should make sure the target directory is always purged, otherwise we risk running out of disk space if a lot of crates fail to build (for example during today's outage).

### PR DESCRIPTION
**Pull request by syphar**
I see this as a temporary solution so we can run the second builder without filling up disk space. Resolves #820 for now. 

The real solution is to refactor the builder structure, probably with the work I'll do related to #1011 .

### CODE REVIEW

File: src/docbuilder/rustwide_builder.rs [hunk 1]
```diff
@@ -363,6 +363,19 @@ impl RustwideBuilder {
...
+        // but for now we chose this simple way to prevent that the build directory remains can
+        // fill up disk space.
+        // This also prevents having multiple builders using the same rustwide workspace,
+        // which we don't do. Currently our separate builders use a separate rustwide workspace.
+        self.workspace
+            .purge_all_build_dirs()
+            .map_err(FailureError::compat)?;
+
         let mut build_dir = self.workspace.build_dir(&format!("{name}-{version}"));
         build_dir.purge().map_err(FailureError::compat)?;
```
Comment (Nemo157) [inline src/docbuilder/rustwide_builder.rs:380]: Do we still need to purge the specific dir if we've purged them all?

Comment (syphar) [reply src/docbuilder/rustwide_builder.rs:380]: hm.. .valid point, yes, I'll remove these.

**Review by Nemo157 — APPROVED** [review]
