### PR TITLE
fixes #1409: internal server error with two slashes at the end of the URL

### LINKED ISSUE #1409: An Internal Server Error occurs if the request URI has two forward slashes after the crate name
An unexpected `HTTP 500 Internal Server Error` response is returned if the request URI has to forward slashes after the crate name, for example:

`https://docs.rs/winapi//`

image

Tested on both Google Chrome and Firefox on Windows 21H1.

Thanks to Legorooj#2455 for bringing this up in the Rust Programming Language Community Server.

### PR DESCRIPTION
**Pull request by syphar**
When iron finds a slash at the end of the route if will try to redirect if the route exists without the slash in the end. 
This leads to an `IronError` which contains a normal permanent redirect as response. 

This is no error for us, we can just return `Ok(error.response)` for these cases.

### CODE REVIEW

File: src/web/mod.rs [hunk 1]
```diff
@@ -167,6 +167,18 @@ impl Handler for MainHandler {
             }
         }
 
+        fn pass_iron_errors_with_redirect(e: IronError) -> IronResult<Response> {
```
Comment (jyn514) [inline src/web/mod.rs:170]: Is there a reason you made this a separate function instead of an inline closure like the other handler?

File: src/web/mod.rs [hunk 2]
```diff
@@ -167,6 +167,18 @@ impl Handler for MainHandler {
...
+            // in some cases the iron router will return a redirect as an `IronError`.
+            // Here we convert these into an `Ok(Response)`.
+            if e.error.downcast_ref::<TrailingSlash>().is_some()
+                || e.response.status == Some(status::MovedPermanently)
+            {
+                Ok(e.response)
```
Comment (jyn514) [inline src/web/mod.rs:176]: Why will there still be a response if there's an error? Also, why does this also handle MovedPermanently? That seems like a change in behavior.

Comment (syphar) [reply src/web/mod.rs:176]: I'm not sure I follow. 

In our own code we do redirects by returning an `Ok(Response)`. Our code expects this and passes this through. 

For this specific case (_URL without slash at the end has a match_, see [the iron source](https://github.com/iron/iron/blob/cde77e5e0e9bfa1bf1230f4bdd8491f4f4cdc72c/router/src/router.rs#L171-L195)), iron returns an `IronError(Response)`. 

Since for us the redirect is fine, and not an error, I want to convert this. 

( of course I could be missing something)

File: src/web/mod.rs (hunk 1 above)
Comment (syphar) [reply src/web/mod.rs:170]: I think it somehow came from the `if_404` handling being in a method. Looking at it now (and after some time), it actually makes more sense as a closure. 

I'll move it.

File: src/web/mod.rs (hunk 2 above)
Comment (jyn514) [reply src/web/mod.rs]: Ok, I think I see - we have our own error handler on *top* of iron's built-in error handlers. And our error handler expects to recognized every possible error, that's what the last `or_else` on line 197 is doing. Since iron has its own built-in error handlers, some of its errors (but not ours) will actually be valid HTTP responses that we can serve without changes.
