### PR TITLE
Separate updating toolchain from adding essential files so they can have different retries

### LINKED ISSUE #2231: Queue was not locked when building `empty-library` failed
```
Sep 22 00:59:23 docsrs cratesfyi[28969]: 2023-09-22T00:59:23.845933Z  INFO docs_rs::docbuilder::rustwide_builder: building a dummy crate to get essential files
[...]
Sep 22 00:59:42 docsrs cratesfyi[28969]: 2023-09-22T00:59:42.825956Z  INFO log: [stderr] error: Unrecognized option: 'disable-per-crate-search' log.target="rustwide::cmd" log.module_pa
[...]
Sep 22 00:59:42 docsrs cratesfyi[28969]: 2023-09-22T00:59:42.827877Z  INFO log: [stderr]   process didn't exit successfully: `/opt/rustwide/rustup-home/toolchains/nightly-x86_64-unknow
[...]
Sep 22 00:59:42 docsrs cratesfyi[28969]: 2023-09-22T00:59:42.931373Z  WARN docs_rs::utils: got error on attempt 1, will try again after 2s:
Sep 22 00:59:42 docsrs cratesfyi[28969]: Updating toolchain failed, locking queue
Sep 22 00:59:42 docsrs cratesfyi[28969]: Caused by:
Sep 22 00:59:42 docsrs cratesfyi[28969]:     failed to build dummy crate for rustc 1.74.0-nightly (b3aa8e716 2023-09-21)
[...]
```

But it continued on to build more crates anyway.

### PR DESCRIPTION
**Pull request by Nemo157**
fixes #2231

### CODE REVIEW

File: src/docbuilder/rustwide_builder.rs [hunk 1]
```diff
@@ -312,7 +309,6 @@ impl RustwideBuilder {
     }
 
     pub fn build_local_package(&mut self, path: &Path) -> Result<bool> {
-        self.update_toolchain()?;
```
Comment (syphar) [inline src/docbuilder/rustwide_builder.rs:315]: this will remove updating (and installing?) the toolchain when you run `cratesfyi build crate ...` locally. 

Is this intentional? 
( I'm not necessarily against it, only wanted to know more)

**Review by syphar — CHANGES_REQUESTED** [review]
I like the change in general, one comment & the build-tests fail

File: src/docbuilder/rustwide_builder.rs (hunk 1 above)
Comment (Nemo157) [reply src/docbuilder/rustwide_builder.rs:313]: Yes. My thoughts were that if you are managing builds manually rather than using the queue builder you should also probably be managing updating the toolchain manually. I could make the `build crate` command do the update itself before the build if you disagree, or add a `--update-toolchain` flag to it to make it controllable.

**Review by syphar — APPROVED** [review]
