### PR TITLE
fix wrong semver redirects with items

### LINKED ISSUE #3036: Version canonicalization redirect adds a spurious trailing slash, resulting in 404
I’m trying to programmatically generate links to the documentation of the latest compatible version of a library. This requires using a partial version specification, which docs.rs will redirect. However, when the link is to an item and not a module, the redirect incorrectly adds a trailing slash. For example, https://docs.rs/itertools/0.14/itertools/trait.Itertools.html (302) will redirect to

https://docs.rs/itertools/0.14.0/itertools/trait.Itertools.html/ (404)

instead of

https://docs.rs/itertools/0.14.0/itertools/trait.Itertools.html (200)

### PR DESCRIPTION
**Pull request by syphar**
fixes #3036

this is more a quickfix, I think I have to structure the whole extractor a little better. But at least it's only one place now :)

### CODE REVIEW

File: src/web/extractors/rustdoc.rs [hunk 1]
```diff
@@ -1682,4 +1697,23 @@ mod tests {
 
         assert_eq!(params.rustdoc_url(), expected_url);
     }
+
+    #[test]
+    fn test_item_with_semver_url() {
```
Comment (GuillaumeGomez) [inline src/web/extractors/rustdoc.rs:1702]: Can you add a comment saying that it's testing that there is no trailing `/` please? Generally, our tests would benefit a lot from having such comments. :)

File: src/web/rustdoc.rs [hunk 2]
```diff
@@ -3464,4 +3464,28 @@ mod test {
 
         Ok(())
     }
+
+    #[tokio::test(flavor = "multi_thread")]
+    async fn test_fetch_item_with_semver_url() -> Result<()> {
```
Comment (GuillaumeGomez) [inline src/web/rustdoc.rs:3469]: Same here.

File: src/web/extractors/rustdoc.rs (hunk 1 above)
Comment (syphar) [reply src/web/extractors/rustdoc.rs:1702]: valid, added

Comment (syphar) [reply src/web/extractors/rustdoc.rs:1702]: valid, added

**Comment by GuillaumeGomez** [comment]
Thanks!
